name: MS-Rewards-Farmer-Docker build and push

on:
  workflow_dispatch:
    inputs:
      chrome_version:
        description: 'Chrome version (eg: 121)'
        required: true
        type: string
      chrome_url:
        description: 'Chrome URL for download (can be find at: https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable)'
        required: true
        type: string
  
env:
  MSR_CHROMEVERSION: ${{ inputs.chrome_version }}
  CHROMEURL: ${{ inputs.chrome_url }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout repository
        uses: actions/checkout@v3
      -
        name: log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            "CHROMEVERSION=${{ inputs.chrome_version }}"
            "CHROMEURL=${{ inputs.chrome_url }}"
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/msr:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/msr:${{ inputs.chrome_version }}
          # https://nova.moe/docker-attestation/
          provenance: false
          sbom: false
